name: Tests

on:
  pull_request:
      branches:
        - master
  workflow_dispatch:
  push:
  release:
    types:
      - created

jobs:
  # This workflow contains a single job called "build"
  tests:
    name: ${{ matrix.test }} (Python ${{ matrix.python }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test: ['TestUtils', 'TestSmall', 'TestMedium', 'TestBig', 'TestAllSoluce']
        python: ['3.9'] # 3.10 seems to fail
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: ${{ matrix.python }}
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -k "${{ matrix.test }}"
